[package]
name = "zeon"
version = "0.0.1"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/Zeon"

[lib]
name = "zeon"
path = "lib.rs"

[dependencies]
tiny-keccak = { version = "2", features = ["sha3", "shake"] }
num_enum = "0.5"
macros = { git = "https://github.com/Berylsoft/rust-macros" }
byterepr = { git = "https://github.com/Berylsoft/byterepr" }

[dev-dependencies]
hex = "*"
hex-literal = "*"
